version: "3.8"

services:
  management-system-api:
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile
    volumes: []
    container_name: management-system-api
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      STAGE: ${STAGE}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:16.14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
